var map_text_data=
{
1:["day 1 - Osaka","Arrivo in serata ad Osaka  - una gradevole antitesi della frenetica e modaiola Tokyo e della vicina e raffinata Kyoto."],
2:["day 2 - Osaka","Castello, Acquario, il quartiere di Dotonbori, Minami"],
3:["day 3 - Osaka - Kyoto","Breve trasferimento via treno per arrivare a Kyoto"],
4:["day 4 - Kyoto","Il Palazzo Imperiale ed il suo giardino, il castello Nijo-jo, i giardini botanici"],
5:["day 5 - Kyoto","Museo internazionale dei Manga, Nintendo Headquarters, Higashima sud"],
6:["day 6 - Kyoto","Higashima nord, ricca di templi, musei, la residenza estiva Shugaku-in Rikyu"],
7:["day 7 - Kyoto - Kanazawa","3 ore di treno per Kanazawa e mezza giornata per vivere questa cittadina nella prefettura di Ishikawa"],
8:["day 8 - Kanazawa - Shirakawago - Takayama","Alpi Giapponesi: Shrakawago, rurale zona di montagna"],
9:["day 9 - Takayama - Nagoya","Breve sosta a Takayama e in viaggio verso Nagoya - Nagoja-jo, lo Sky Balcony ed il giardino Noritake"],
10:["day 10 - Nagoya","In bus verso Tsumago e Magone per percorrere l’antica via dei samurai (circa 7 km) "],
11:["day 11 - Nagoya - Tokyo","Ultimo breve viaggio in treno per raggiungere la capitale!"],
12:["day 12 - Tokyo","Santuario Meiji-jingu di Harajuku, fiume Omote-sando, quartiere di Shibuya e Shinjuku"],
13:["day 13 - Tokyo","Mercato del pesce di Tsukiji, il giardino Hama-rikyu Onshi-teien, Ginza, Kabuki-za"],
14:["day 14 - Tokyo","Escursione a Nikko, per vedere il santuario Nikko Toshogu (patrimonio dell’UNESCO), le cascate Keon ed il lago Chuzenji"],
15:["day 15 - Tokyo","Quartieri “antichi”: Asakusa, Ueno, Yanaka, Shinsuke."],
16:["day 16 - Tokyo","Visita all’area del monte Fuji, percorrendo diverse stazioni del monte. Visita al lago Ashi e risalita sul monte Komagatake con vista sull’Hakone National Park. "],
17:["day 17 - Tokyo","Quartieri anticonformisti - Shimo-Kitizara, Akihabara, Roppongi"],
18:["day 18 - Tokyo","Museo Ghibli, Yanaka"],
}